name: Deploy to Azure Blob Storage

on:
  push:
    branches: [ main ]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        submodules: 'true'
    - name: Install Hugo
      env:
        HUGO_VERSION: '0.147.7'
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb \
        && sudo dpkg -i ${{ runner.temp }}/hugo.deb
    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
    - name: Install dependencies
      run: npm ci
    - name: Build site
      env:
        AZURE_STORAGE_CONNECTION_STRING: ${{ secrets.IMAGE_ACCOUNT_CONNECTION_STRING }}
        AZURE_STORAGE_CONTAINER_NAME: ${{ secrets.IMAGE_CONTAINER_NAME }}
      run: npm run build --if-present
    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: site
        path: public/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Login
      uses: Azure/login@v2.3.0
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Download artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: site
        path: public
    - name: Upload static site
      uses: Azure/cli@v2.1.0
      with:
        inlineScript: |
          az storage blob upload-batch --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} --auth-mode login --overwrite true -d '$web' -s public
    - name: Purge CDN
      uses: Azure/cli@v2.1.0
      continue-on-error: true
      with:
        inlineScript: |
          az afd endpoint purge --content-paths '/*' -g ${{ secrets.RESOURCE_GROUP }} --profile-name ${{ secrets.AFD_PROFILE_NAME }} --endpoint-name ${{ secrets.AFD_ENDPOINT }}
    - name: Logout
      run: |
        az logout
      if: always()
